version: "3"

services:
  nginx:
    image: nginx:1.12.1-alpine
    container_name: cb_nginx
    ports:
      - "5555:80"
    links:
      - node
    volumes:
      - .:/usr/src/app
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf

  node:
    container_name: cb_node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    links:
      - mongo
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    container_name: cb_mongo
    image: mongo:3.4.8
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    command: mongod --smallfiles --logpath=/dev/null
